### ISSUE TITLE
Design: UI revamp of contributors and about-us tabs

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/hackfest-flutter#43]
### Description:
The current user interface for the contributors and about us tabs needs a visual update. This issue aims to improve the overall look and feel of these sections to align with the theme and colour palette of Hacktoberfest23.

### Tips for the issue:
- Redesign the user interfaces of the contributors and about us tabs.
- Apply the Hacktoberfest23 theme and colour palette.
- Ensure consistency in styling across all tabs.
- Feel free to make major UI changes.

### To do:
- [ ] Ask us to assign the issue
- [ ] Once the issue is assigned, you can start working on it
- [ ] Create a PR

### Resource:
- [Material 3 Design](https://m3.material.io/) 
- [Flutter UI docs](https://docs.flutter.dev/ui) 

### Notes:
The task is **assigned to contributors on a first-come, first-serve basis**, and the **contributor has to report progress every 3 days** to ensure active development on the tasks.

**Comment by shirshakk** [comment]
Hi @dk-a-dev,

I have recent experience with Flutter and am enthusiastic about contributing to Hacktoberfest. Please assign me this issue. Eager to collaborate and learn. Thanks!

**Comment by dk-a-dev** [comment]
hi @shirshakk ,i have assigned it to you, please stick to note mentioned and also contributing guidelines, looking forward for ur PR

**Comment by shirshakk** [comment]
@dk-a-dev I have done with the issue, please review it

**Comment by dk-a-dev** [comment]
@shirshakk plz file a pr again or plz response with a progress

**Comment by shirshakk** [comment]
Sorry sir will not able to continue the work

**Comment by SarveshChavan** [comment]
Hey @dk-a-dev I can provide the UI design for this pages and also for the app too. Can I take on this issue then? 
If you feel this good we can do one thing, create a figma design share the link and give me the access to update it and I'll add the figma design for the screens.

**Comment by dk-a-dev** [comment]
@SarveshChavan yup buddy I can do that,
I will create separate issues for design and separate for implementation of those designs just give me a little time I will create issues and will add figma file and also will assign u
