### ISSUE TITLE
Design: UI revamp for splash screen

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/hackfest-flutter#44]
### Description:
The app's splash screen is the first thing users see, and it should make a positive impression. This issue involves redesigning the splash screen to provide a visually appealing and engaging introduction to the app.

### Tips for the issue:
- Create a new design for the splash screen and make sure to retain the hacktoberfest’23 logo
- Ensure the splash screen loads quickly and smoothly.

### To do:
- [x] Ask us to assign the issue
- [x] Once the issue is assigned, you can start working on it
- [x] Create a PR

### Resource:
- [pub.dev/splash_screen](https://pub.dev/packages/animated_splash_screen)
- [Flutter UI docs](https://docs.flutter.dev/ui) 
- [hacktoberfest logo circular](https://hacktoberfest.com/_next/static/media/logo-hacktoberfest--logomark.b91c17d2.svg)
- [hacktoberfest logo horizontal](https://hacktoberfest.com/_next/static/media/logo-hacktoberfest--horizontal.ebc5fdc8.svg)

### Notes:
The task is **assigned to contributors on a first-come, first-serve basis**, and the **contributor has to report progress every 3 days** to ensure active development on the tasks.

**Comment by VertikaBajpai** [comment]
Hello @dk-a-dev  , I have recently worked on frontend in Flutter. I would like to contribute , please assign me this issue..

**Comment by dk-a-dev** [comment]
Hi @VertikaBajpai , i am assigning this issue to you, please stick to the note mentioned
Happy Designing :)

**Comment by ayushgit2003** [comment]
Hi @dk-a-dev, I want to work in this issue please assign

**Comment by dk-a-dev** [comment]
Hello @ayushgit2003 , this issue is already assigned , look for other issues in this repo or other ieee repos, I will soon be adding more issues

**Comment by dk-a-dev** [comment]
@VertikaBajpai progress report

**Comment by VertikaBajpai** [comment]
@dk-a-dev Can you please clarify if this repo is still included in Hacktoberfest bcoz on my Github it is showing that the repo is excluded from Hacktoberfest and it won't count

**Comment by dk-a-dev** [comment]
> @dk-a-dev Can you please clarify if this repo is still included in Hacktoberfest bcoz on my Github it is showing that the repo is excluded from Hacktoberfest and it won't count

Can u please share ss

**Comment by VertikaBajpai** [comment]
@dk-a-dev Yes sure . Here it is...
![image](https://github.com/IEEE-VIT/hackfest-flutter/assets/119621037/62d65c99-37ad-4a98-8a32-427660a801b9)


![Screenshot (19)](https://github.com/IEEE-VIT/hackfest-flutter/assets/119621037/50a0f475-b440-49e7-ae90-bf3a26fff594)
