### ISSUE TITLE
Feature: connecting search and contributors page

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/hackfest-flutter#45]
### Description:
Currently, there's a disconnect between the search and contributors pages. After a successful search, users should be able to seamlessly see contributors of the selected repository.

### Tips for the issue:
- Implement a button or link on the search results page to access the contributors.
- Ensure that clicking the button provides users with information about the contributors of the selected repository.

### To do:
- [x] Ask us to assign the issue
- [x] Once the issue is assigned, you can start working on it
- [x] Create a PR

### Resource:
- [Material 3 Design](https://docs.flutter.dev/ui/widgets/material) 
- [Flutter Navigation and routing docs](https://docs.flutter.dev/ui/navigation) 

### Notes:
The task is **assigned to contributors on a first-come, first-serve basis**, and the **contributor has to report progress every 3 days** to ensure active development on the tasks.

**Comment by ekakshjanweja** [comment]
Hey, is anyone working on this?

**Comment by dk-a-dev** [comment]
No u can work on this i will assign this to u
Make sure to keep note NOTED!! 
Happy Coding:)

**Comment by ekakshjanweja** [comment]
@dk-a-dev Cool, I will start looking around.

**Comment by ekakshjanweja** [comment]
@dk-a-dev Hey just a small question what flutter version are we guys using?

**Comment by dk-a-dev** [comment]
Latest just switch to latest
check yaml file

**Comment by dk-a-dev** [comment]
@ekakshjanweja any updates on issue?

**Comment by ekakshjanweja** [comment]
Sorry won't be able to work on this and got some other commitments 🙏

**Comment by Lomesh21** [comment]
Hey, I have gone through the repo and i have a small doubt. When we search repository and after clicking on that repository if we give a button there which will navigate to contributors of repository page. Can we do this instead of the bottom navigation bar button for contributors?

**Comment by dk-a-dev** [comment]
@Lomesh21 seems like a good idea, are you interested in working on it, I can create a separate issue or extend the scope of current one, whatever u wish, or u can check out #49 and ask me to assign you to work on that, current PR on that is not impressive enough

**Comment by dk-a-dev** [comment]
@Lomesh21 Its assigned, happy coding, keep me posted and if u need any help feel free to reach out

**Comment by Lomesh21** [comment]
@dk-a-dev Definitely

**Comment by Lomesh21** [comment]
@dk-a-dev 
I have made changes, just to confirm, i am attaching a video please go through it and let me know if this works or not

https://github.com/IEEE-VIT/hackfest-flutter/assets/94422862/acf7300f-c0a0-4909-8ee8-2569c00b0753

**Comment by dk-a-dev** [comment]
@Lomesh21 good work the ui is fine u can continue ur work

**Comment by dk-a-dev** [comment]
@Lomesh21 keep in mind to keep ur branch update with the master commits and pull frequently

**Comment by Lomesh21** [comment]
@dk-a-dev Yes I will,
I am just adding video, just check it out and let me know, is it resolving issue because through issue description i thought it is completed now..
So please check it out once

https://github.com/IEEE-VIT/hackfest-flutter/assets/94422862/3a6b7b00-3e00-471d-a596-c1a04878daad

**Comment by dk-a-dev** [comment]
@Lomesh21 seems  good, file a pr then only I can review ur code and give more detailed feedbacks

**Comment by Lomesh21** [comment]
Okay I will do it now
