### ISSUE TITLE
Feature: repository bookmarking

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/hackfest-flutter#46]
### Description:
To improve user experience, users should have the ability to bookmark repositories they find interesting or plan to contribute to. This feature will allow users to easily access their favourite repositories later.

### Tips for the issue:
- Design and add a bookmark icon to repository cards.
- Create a "Bookmarks" section in the app.
- Implement the ability to add/remove repositories from bookmarks.
- Make sure bookmarked repos remain persistent in the bookmark tab

### To do:
- [x] Ask us to assign the issue
- [x] Once the issue is assigned, you can start working on it
- [x] Create a PR

### Resource:
- [Material 3 Design](https://m3.material.io/)
- [Flutter UI docs](https://docs.flutter.dev/ui)
- [Storing Data](https://docs.flutter.dev/cookbook/persistence)

### Notes:
The task is **assigned to contributors on a first-come, first-serve basis**, and the **contributor has to report progress every 3 days** to ensure active development on the tasks.

**Comment by Yash-Waghmare** [comment]
Hey @dk-a-dev, I have gone through this repo and would like to work on this issue.

**Comment by dk-a-dev** [comment]
Hello @Yash-Waghmare, its is assigned to u please make sure to stick to note mentioned 
For any help you can reach me out
Happy coding

**Comment by TheScriptRailoth** [comment]
Hello @dk-a-dev, I want to work on this issue.

**Comment by Yash-Waghmare** [comment]
It will be great to work together @TheScriptRailoth, let's join on Discord, my ID is yash_7714

**Comment by TheScriptRailoth** [comment]
> It will be great to work together @TheScriptRailoth, let's join on Discord, my ID is yash_7714

Sure

**Comment by dk-a-dev** [comment]
@Yash-Waghmare , @TheScriptRailoth 
Progress report??

**Comment by Yash-Waghmare** [comment]
> @Yash-Waghmare , @TheScriptRailoth Progress report??

Working on the issue, currently, I am only working on the issue.

**Comment by Yash-Waghmare** [comment]
For persistent data, could we use shared preferences?

**Comment by dk-a-dev** [comment]
@Yash-Waghmare yup go ahead

**Comment by dk-a-dev** [comment]
@Yash-Waghmare sorry for the repo lockdown, we were fixing the issue of repo not showing up for hacktoberfest, its fixed now

**Comment by dk-a-dev** [comment]
@TheScriptRailoth u are unassigned for not being active

**Comment by Yash-Waghmare** [comment]
> @Yash-Waghmare yup go ahead

okay

**Comment by dk-a-dev** [comment]
@Yash-Waghmare I expect progress? please keep me in the loop

**Comment by Yash-Waghmare** [comment]
Functionality is being added, now focusing on UI improvement.

**Comment by Yash-Waghmare** [comment]
Hey @dk-a-dev,  I apologize for the delay in delivering the code. I have completed the implementation and I would appreciate it if you could review it and let me know if there are any issues or improvements needed.

I also encountered a problem with the bookmark icon button. It does not change its state as expected. I suspect that the FlutterSlimyCard is causing this problem. However, changing the card style would require removing the FlutterSlimyCard package.

Do you have any suggestions on how to solve this problem?

![ScreenRecorderProject2](https://github.com/IEEE-VIT/hackfest-flutter/assets/74498638/682c22cf-dcfc-4ce8-b6cd-dc68f4ac2573)

**Comment by dk-a-dev** [comment]
@Yash-Waghmare buddy I can't tell anything without seeing the code, ur video only shows u scrolling through the search page, can u plz add more insights

**Comment by dk-a-dev** [comment]
If u r done with making ui and implementing make a pr I will review it and will also suggest u improvements and changes

**Comment by dk-a-dev** [comment]
Also ur branch is too behind from master so before filing a pr make sure to pull from master resolve conflicts from ur end I suggest to fork the master into a new folder see what commits changes are already been made then see how u can resolve stuff by retaining ur and masters changes

**Comment by Yash-Waghmare** [comment]
okay got it, I will do it

**Comment by Yash-Waghmare** [comment]
Hey @dk-a-dev, I have raised the PR, will you please check it, and tell me changes if there are any?
