### ISSUE TITLE
Feature: implement display according to user default system theme

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/hackfest-flutter#47]
### Description:
Currently, the app lacks support for adapting its display to the user's system theme preference. To enhance user experience and align with user expectations, we should implement the ability to automatically switch between light and dark themes based on the user's system-wide preference and also add it to settings to change manually

### Tips for the issue:
- You can edit the icon on top to write and implement it.
- Feel free to change the UI
- Making a settings page screen and implementing it there is my recommendation

### To do:
- [x] Ask us to assign the issue
- [x] Once the issue is assigned, you can start working on it
- [x] Create a PR

### Resource:
- [Flutter docs](https://docs.flutter.dev) 

### Notes:
The task is **assigned to contributors on a first-come, first-serve basis**, and the **contributor has to report progress every 3 days** to ensure active development on the tasks.

**Comment by dk-a-dev** [comment]
Hi @0kt1 , would love to see your experience, improving our UX, I am assigning this issue to you, make sure to stick to notes mentioned in the issue and read CONTRIBUTING.md and README.md
Happy Coding:)

**Comment by shirshakk** [comment]
Hi @dk-a-dev,

I have recent experience with Flutter and am enthusiastic about contributing to Hacktoberfest. Please assign me this issue. Eager to collaborate and learn. Thanks!

**Comment by dk-a-dev** [comment]
Hello @shirshakk , this issue is already assigned, if the current assignee is unable to solve the issue I will assign it to you
feel free to check out other issues as there are a lot of good-first-issues, check out our other repos for more..
