### ISSUE TITLE
Fix: enhance contributors page UX

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/hackfest-flutter#49]
### Description:
Currently, the contributors page lacks visual engagement when no repository is searched, and there is a lack of feedback during data retrieval. To improve user experience, we should add a static animation when no repository is searched and implement a loading spinner while fetching data.

### To do:
- [ ] Ask us to assign the issue
- [ ] Once the issue is assigned, you can start working on it
- [ ] Create a PR

### Resource:
- [Flutter docs](https://docs.flutter.dev) 

### Notes:
The task is **assigned to contributors on a first-come, first-serve basis**, and the **contributor has to report progress every 3 days** to ensure active development on the tasks.

**Comment by Imsurajr** [comment]
Hello, I would like to work on this issue.

**Comment by dk-a-dev** [comment]
Hi @Imsurajr , i am assigning this issue to you, male sure to read CONTRIBUTING.md and also stick to the note
Happy Coding!!:)

**Comment by Imsurajr** [comment]
Hello, thanks for assigning me this issue, I have started working on it.

**Comment by zykuriku** [comment]
i would like to work on this issue if it can still be assigned

**Comment by dk-a-dev** [comment]
hey @zykuriku, this issue is already assigned, please look for other issues on this repo, also checkout other repos on IEEE

**Comment by dk-a-dev** [comment]
@zykuriku this issue is now assignable, please tell me your ideas for the issue
