### ISSUE TITLE
Contributors page throws FormatException

### ISSUE THREAD

**Issue by Riktam-Santra** [IEEE-VIT/hackfest-flutter#57]
**Describe the bug**
The Contributors tab throws FormatException as soon as it is opened

**To Reproduce**

1. Open App
2. Tap on the contributors tab
3. See Error

**Expected behavior**
There should be no exception thrown and the app should continue to fetch data and display it normally

**Screenshots (Optional)**

![Code_h05o1W3mYI](https://github.com/IEEE-VIT/hacktoberfest-flutter/assets/32616925/211b1bdc-9419-4430-b43c-2fd11d03b7f6)

**Comment by sosualfred** [comment]
Hello, I would like to work on this issue.

**Comment by dk-a-dev** [comment]
> Hello, I would like to work on this issue.

@sosualfred sorry buddy this issue already has a PR
