### ISSUE TITLE
Fix: searching repos with null character

### ISSUE THREAD

**Issue by SarveshChavan** [IEEE-VIT/hackfest-flutter#65]
**Describe the bug**
When we want to look for a repo we search the repo name or related topics, but when the user searches a string of only space characters the app throws an exception. 

**To Reproduce**

1. Go to the Search Bar
2. Click on Search and add the string "    "
3. See error

**Expected behavior**
Nothing should be searched and no API call should be made

**Screenshots (Optional)**
![image](https://github.com/IEEE-VIT/hackfest-flutter/assets/103113615/2389412e-b648-4fe1-b2ae-372290ca6a1c)

**Comment by SarveshChavan** [comment]
If you want to solve this issue I can work on it

**Comment by dk-a-dev** [comment]
@SarveshChavan yup go ahead fix this one
