### ISSUE TITLE
Docs: adding app workflow and functioning in README.md

### ISSUE THREAD

**Issue by SarveshChavan** [IEEE-VIT/hackfest-flutter#66]
### Description
Adding app workflow in the README.md so that new contributors can easily understand the app. This will help ensure that everyone is on the same page and that the app is being developed in a consistent and efficient manner.

### Describe the Solution
Using [Mermaid JS](https://mermaid.js.org/) as a tool make app workflow diagram

### Resources:
- [Mermaid JS Docs](https://mermaid.js.org/intro/getting-started.html)
- Using **Extension: [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)** for vscode

**Comment by SarveshChavan** [comment]
If you find this feature interesting, I would love to work on it.

**Comment by dk-a-dev** [comment]
@SarveshChavan 
The thing you are talking about is... [Github Templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
M I correct

**Comment by SarveshChavan** [comment]
I guess not, I'm talking about creating a readme file that will showcase the app states such as

Click on App -> SplashScreen() ->HomePage -> Option1: SearchRepo() Click Search Button, Option2:Change Color Theme, Option3: Click About Us, Option4: Click Contributors() 

and so on 
such that one can understand the flow by reading the file, we can also mention API calls and what the API calls returns

**Comment by dk-a-dev** [comment]
@SarveshChavan yeh got it work on it and feel free to reach out if u need help in understanding workflow of the app or anything

**Comment by SarveshChavan** [comment]
I have created the app flow file review it when you get free and also reach out to me if any thing needs to be inserted or to be removed from the file.

**Comment by dk-a-dev** [comment]
I will sort out this one by tomo

**Comment by dk-a-dev** [comment]
@SarveshChavan refer #87
