### ISSUE TITLE
Fix: text alignment in repo cards

### ISSUE THREAD

**Issue by SarveshChavan** [IEEE-VIT/hackfest-flutter#67]
**Describe the bug**
In the Repo Card, the description is not given specific alignments, whenever the description is small or big it affects the UI.

**To Reproduce**

1. Go to the Search Bar
2. Search for a Repo
3. Check the Repo Card and view its description
4. See the problem

**Expected behavior**
We should use the proper alignment so that the description will not look weird in context with other widgets. 

**Screenshots (Optional)**
![image](https://github.com/IEEE-VIT/hackfest-flutter/assets/103113615/1b527123-c1d0-4daf-8bfd-3e3f32669f21)

**Comment by SarveshChavan** [comment]
Can I take on this Issue?

**Comment by dk-a-dev** [comment]
@SarveshChavan yup its urs
Please keep me in the loop, also if u can improve repo card UI/UX that would be grt

**Comment by SarveshChavan** [comment]
This PR is having conflicts so I recommend to kindly check it on priority as I created a Button widget for efficient use. Also if you have any suggestions to change the PR so as it won't create conflicts please do share with me and I'll update the PR accordingly.

**Comment by dk-a-dev** [comment]
@SarveshChavan i am on it dw

**Comment by SarveshChavan** [comment]
I can do one thing, I will resolve the merge conflicts and I'll only change the alignment of text in the repo card and the custom button widget will be there but I won't use it in this PR. We can use it later.
