### ISSUE TITLE
Creation of Profile Page

### ISSUE THREAD

**Issue by Lomesh21** [IEEE-VIT/hackfest-flutter#81]
Creation of profile page as user logged in the app, user will see the details.

Page will be created as per figma design.

**Comment by dk-a-dev** [comment]
@Lomesh21 add placeholders instead network images
![image](https://github.com/IEEE-VIT/hackfest-flutter/assets/84137299/bcd23f24-c611-448e-b243-2715eb4fb203)

**Comment by Lomesh21** [comment]
Okay  @dk-a-dev  , I will do that now onwards

**Comment by Lomesh21** [comment]
Hey @dk-a-dev we can't use placeholder at the place of network image, and we have to fetch network image from github api so it will be beneficial if we use network image, instead of doing place holder l, I will add TODOs after network image so, we get to know where we have to change the url

**Comment by dk-a-dev** [comment]
ok that also works, anyway person implementing fetching could easily do that ur wish
