### ISSUE TITLE
App Drawer Integration with theme change

### ISSUE THREAD

**Issue by Lomesh21** [IEEE-VIT/hackfest-flutter#84]
The App drawer is not integrated with theme changes

![image](https://github.com/IEEE-VIT/hackfest-flutter/assets/94422862/6dd07949-150f-43ea-96a9-49b858cbfaa1)

**Expected behavior**
Change it according to figma design
![image](https://github.com/IEEE-VIT/hackfest-flutter/assets/94422862/94eb2ff8-5a18-42ea-b9a0-a37de510e87c)

**Comment by Lomesh21** [comment]
@dk-a-dev  I will resolve the bug as the drawer assigned to me and the Profile page is yet to complete so, it will be beneficial if we resolve this bug early to maintain the flow of developement

**Comment by dk-a-dev** [comment]
![Screenshot_2023-10-30-10-07-30-22_37f5c2e3657a99a69dbab9a0f92f640b.jpg](https://github.com/IEEE-VIT/hackfest-flutter/assets/84137299/4d96c8b5-e030-49c7-a250-4d62f6df8c8e)

![Screenshot_2023-10-30-10-07-27-15_37f5c2e3657a99a69dbab9a0f92f640b.jpg](https://github.com/IEEE-VIT/hackfest-flutter/assets/84137299/a309e0e3-5a6f-4e74-8d3d-b318c6377183)

@Lomesh21 it's integrated @SarveshChavan did it

**Comment by dk-a-dev** [comment]
Close as completed

**Comment by Lomesh21** [comment]
@dk-a-dev it is not as per figma design na?

**Comment by Lomesh21** [comment]
The PR that @SarveshChavan  gave is all about Search repos we discussed that and he didn't resolve about app drawer

**Comment by dk-a-dev** [comment]
Ya but the blue colour looks better than black

**Comment by Lomesh21** [comment]
Okay then I thought it should be like figma design
